### ISSUE TITLE
annotation hover display from static annotation list seems buggy

### ISSUE THREAD

**Issue by jeffreycwitt** [IIIF/mirador#1064]
I just pulled in the 2.1 release candidate. Things look really great. 

However, I noticed that I started to get different behavior when the mouse hovers over an annotation region. The annotation associated with the region only appears to be popping up for some (or just one) of the annotation regions. (In this example, annotations come from an annotation list connected to the Canvas). See GIF below. You can use the following manifest for testing: http://scta.info/iiif/pp-sorb/manifest 

![mirador-annotation-bug](https://cloud.githubusercontent.com/assets/1146685/17909530/d2f63daa-6952-11e6-97b9-6e008dad5672.gif)

**Comment by jeffreycwitt** [comment]
More testing suggests that viewer is only allowing one of the regions on each canvas to have a pop up annotation display. (in other words, as I move from canvas to canvas, only one of the regions provides a mouseOver display. The region that works on any given canvas seems to be random)

**Comment by rsinghal** [comment]
@radpet Can you take a look as well?

**Comment by radpet** [comment]
Just a quick run gives me that https://github.com/IIIF/mirador/blob/release2.1/js/src/annotations/osd-region-draw-tool.js#L125 shows only shape associated with the annotation (the one that the hover works on)

**Comment by rsinghal** [comment]
@jeffreycwitt I think the problem is that your annotations don't have unique @id for each annotation in your annotationList.  We use that id to keep track of the annotations in a map, so that is why, on the first page, only the annotation on the bottom right is showing the annotation when you hover over.  The Ege manifest from Stanford, https://github.com/IIIF/mirador/tree/add_iiif_manifest_layouts, uses unique ids, and doesn't have the same issue.

**Comment by jeffreycwitt** [comment]
Ahh, ok. That's a bug on my end. Sorry about that. I've updated my lists and everything works now. with this manifest now: http://scta.info/iiif/pp-sorb/manifest

Thanks :)
