### ISSUE TITLE
Mouseover in ManifestsPanel should show full label

### ISSUE THREAD

**Issue by azaroth42** [IIIF/mirador#287]
Otherwise when the first part is the same, the title isn't useful and there's no way to get to it.

![screen shot 2014-10-10 at 6 27 08 pm](https://cloud.githubusercontent.com/assets/871868/4600973/d336799c-50e5-11e4-9422-33a603f6e096.png)

**Comment by regisrob** [comment]
+1. Would be nice for first m2 release (at least by providing a tooltip when there is not enough space to display the manifest label AND the preview)
Moreover, manifest labels should use as much space as possible (see screenshot below):
![capture d ecran 2015-03-09 a 17 53 18](https://cloud.githubusercontent.com/assets/402117/6559811/c0a905b8-c685-11e4-9418-0454e11be6a3.png)

**Comment by regisrob** [comment]
Another example here: http://demos.biblissima-condorcet.fr/florus/manuscrits-florus/mirador/index.html
IMO having the full label (at least if it's not too long) is quite critical.

**Comment by aeschylus** [comment]
Yep. I have a re-design of this that will take care of this issue. I'll post some images here today.

**Comment by regisrob** [comment]
Cool :wink: I'll have a look tomorrow

**Comment by aeschylus** [comment]
![load menu](https://cloud.githubusercontent.com/assets/145874/7397234/eb48c440-ee5b-11e4-9887-d55a12e2af14.png)

### Hover States
![mockup](https://cloud.githubusercontent.com/assets/145874/7397277/23a2d6aa-ee5c-11e4-9eac-b205db5bfc61.png)

**Comment by regisrob** [comment]
Good re-design, seems appropriate to me

**Comment by jvine** [comment]
I had been playing with this layout in parallel - here is what I came up with, and at least some of the rationale.

![mirador-load-window-layout](https://cloud.githubusercontent.com/assets/6945691/7761319/3b2a2e20-ffd9-11e4-9a32-924e2db3c672.png)

- I think the use of the left sidebar is a poor use of space, and closely groups two input controls that actually behave differently. So:
 - Move the controls above the list
 - Align the filter input with the content that it filters
 - Remove the redundant placeholder text from the filter input
 - Separate the load feature to the right
 - Easy to disable/hide the load feature without unbalancing the page, if that's appropriate in certain contexts
- IMO the background transparency introduces visual noise and makes it harder to read and focus on the elements of this page. Try using box-shadow to communicate layers - maybe bring the window in a bit further from the top and side borders. 
- Stretching the title above the image row will give it more room, but it also means a lot of eye movement to read the complete title. 
 - Wrap the text to three (say) lines, then truncate using line-height. If you want to get fancy you can programmatically add an ellipsis. 
 - Give it a min and max width to maintain readability.
 - Potentially add a clickable "more…" link that increases the height of the row (see second truncated title). This gives you a focusable element that a keyboard-only user can get to, and places the expansion in the user's direct control.
 - A hover mdoe that shows the whole title is another option, but I'm not sure how this would work for keyboard accessiblity, and again (at least in the mockup) it introduces transparency, specifically making the revealed text less readable.
- Is the institutional logo really such an important element? The partial transparency helps mute it a bit; I'm just curious if it's intentionally so prominent - it could be a lot smaller without losing the overall message of "this list has mostly Harvard mss" (or whatever).
- The math (x number of images - y images shown = z more) is a distraction - a little cognitive detail that distracts from the overall thing that you're communicating, which is:  There are 643 images in this object, and here's a preview.
 - Removing the "z more" number will let you make the row more gracefully responsive, so that images can drop out individually as the viewport gets narrower, say to some minimum threshold (equivalent to xs device) where they finally wrap below the text content.
 - The texture behind the "z more" section is noise again… I'd just replace the whole block with a subtle ellipsis. Or you could partially obscure the right-most image so it is "disappearing" off the edge? May not be as clear.
- I like showing the number of annotations; but it seems more appropriate to group it with the total number of images rather than the repository name - unless they are specific to the repository?
- The heading structure of this page is strange. Virtually all elements are headings, and they are at odd levels - I think they are just being used to set font size…? I think only the manifest titles should be headings; everything else is just... content. (Although the page as a whole could use a "you are here" kind of heading, too.)

![mirador-load-window-headings](https://cloud.githubusercontent.com/assets/6945691/7761347/a0166fe2-ffd9-11e4-8b67-62e2a8f1ffb0.png)

**Comment by azaroth42** [comment]
Not sure where the annotation number comes from. That seems extremely expensive, if not impossible, to compute. Can we leave it off the mocks until someone can actually describe how it could be generated?

**Comment by azaroth42** [comment]
Otherwise :+1: to everything Jennifer says!

**Comment by regisrob** [comment]
:+1:
* the institutional logo is important but I think it is sufficiently apparent in the new mocks
* if it's not possible to get the number of annotations, maybe we could just indicate that a manifest has annotations ?
* removing the "z more" is a good idea (especially as it does not translate well... at least in French: I've set "restants" but it seems quite unusual to me...: https://github.com/regisrob/mirador/blob/internationalization/locales/fr/translation.json)

**Comment by rsinghal** [comment]
Agree with Rob, no to displaying # of annotations on this page.  The rest seems reasonable.
