### ISSUE TITLE
Image URLs are returned as .jpg regardless of mime type in manifest 

### ISSUE THREAD

**Issue by pobocks** [IIIF/mirador#517]
According to http://iiif.io/api/image/2.0/#image-request-uri-syntax, format specifiers other than jpg should be handled.  However, in the URL generation code ([hereabouts](https://github.com/IIIF/mirador/blob/master/js/src/utils/iiif.js#L28)), the format specifier is being set to .jpg regardless of anything in the manifest.

My theory on the right thing to do: use a hash of mime types that work with OpenSeadragon I'm actively working on this - should have a pull request soon.

**Comment by azaroth42** [comment]
:-1:
I disagree that this is an issue.  IIIF servers MUST support jpg as a format at all levels of compliance:
See http://iiif.io/api/image/2.0/compliance.html#format

And thus if there is a IIIF service associated with an image resource, then using the jpg format should always work.

Recommend: wontfix

**Comment by aeschylus** [comment]
I agree with Rob that this would add complexity without much benefit. Jpeg can be dependably expected from every server.

**Comment by pobocks** [comment]
We might be unique, in having significant image resources that don't have
jpg deliverables, but it seems like the amount of work is small enough
(it's a few lines in iiif.js and two lines in utils.js) that it's worth
doing for the benefit of people with large sets of legacy image assets (or,
as in our case, services that do cheaper tif->gif conversion) or preferred
formats that aren't jpg.

After all, even if .jpg is guaranteed by the standard, is silently failing
to use alternate formats where available and requested really the right
thing to do?  And at some point it has to start caring for level 3
compliance, unless I'm misunderstanding something?

PR added to illustrate, not in expectation of being merged.

**Comment by azaroth42** [comment]
Still :-1: to guessing a format, based on a potentially unrelated URI's
format (static thumbnail in a cache vs a IIIF service driven from a
different master), rather than selecting from the list of formats available
from the service.

In this situation, you would need to either:
 a. Eat the cost of requesting info.json for every thumbnail to find out
which formats are supported
 b. Include that information in the manifest for every canvas

Basically, if the implementation doesn't support "jpg" in the format slot,
it's not conformant with the specification.  Every level of conformance
requires a jpg formatted version to be available. OpenSeadragon also simply
requests JPGs on the same basis, as per:

https://github.com/openseadragon/openseadragon/blob/master/src/iiiftilesource.js#L240

So you're not gaining anything anyway as you won't be able to see the image
in the main view either, regardless of getting a thumbnail.

From a specification perspective, you can't even create a valid info.json
response as the first profile MUST be the minimum supported profile from
the compliance levels, and you don't even support level0.  Sorry!

As a horrific work around you could redirect .jpg to .gif (or whatever) on
your server.


On Mon, Apr 13, 2015 at 4:29 PM, pobocks <notifications@github.com> wrote:

> We might be unique, in having significant image resources that don't have
> jpg deliverables, but it seems like the amount of work is small enough
> (it's a few lines in iiif.js and two lines in utils.js) that it's worth
> doing for the benefit of people with large sets of legacy image assets (or,
> as in our case, services that do cheaper tif->gif conversion) or preferred
> formats that aren't jpg.
>
> After all, even if .jpg is guaranteed by the standard, is silently failing
> to use alternate formats where available and requested really the right
> thing to do? And at some point it has to start caring for level 3
> compliance, unless I'm misunderstanding something?
>
> PR added to illustrate, not in expectation of being merged.
>
>
> On Mon, Apr 13, 2015 at 3:31 PM, aeschylus <notifications@github.com>
> wrote:
>
> > I agree with Rob that this would add complexity without much benefit.
> Jpeg
> > can be dependably expected from every server.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/IIIF/mirador/issues/517#issuecomment-92471415>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/IIIF/mirador/issues/517#issuecomment-92532727>.
>



-- 
Rob Sanderson
Information Standards Advocate
Digital Library Systems and Services
Stanford, CA 94305

**Comment by azaroth42** [comment]
(recommend close wontfix)

**Comment by rsinghal** [comment]
per https://github.com/IIIF/iiif.io/issues/449, won't fix
