### ISSUE TITLE
When using "Add via URI" feature, slot[n].window is null

### ISSUE THREAD

**Issue by pobocks** [IIIF/mirador#573]
As of most recent master (6aaaf41045d7d3624a9266d18825aa734f550a21), any manifest added via URL insertion is successfully added, but the slot that its window is in doesn't has a window property.

This is important to us because, in the absence of an explicit API to query Mirador state, we're essentially having to do 

```javascript
var slots = Mirador.viewer.workspace.slots;
for (var i = 0; i < slots.length; i++) {
  slot[i].window //We do stuff with this
}
```

**Comment by aeschylus** [comment]
I'm not sure I understand the bug. 

Using current master, I have rebuilt, added a manifest from URL from e-codices after selecting the slot to fill, and clicked on a thumbnail, which causes that manifest to open at the appropriate page in the window. It also behaves as expected when selecting the title of the manifest, opening in thumbnail view.

Tangentially, you can query the complete Mirador state at any time using:
````
var state = Mirador.saveController.currentConfig;
````

What exactly are you trying to accomplish? Getting all windows? 

```` 
var windows = Mirador.viewer.workspace.windows; // returns an array of all window objects

// To get the slot:
var mySlot = windows[index].parent;

// Get a slot "visually" from its layout address
var leftSlot = Mirador.viewer.workspace.getSlotFromAddress('row1.column2'); // left slot of 1x2 layout
````

In general Mirador objects have few private variables and the object hierarchy is rational and reflects the visual interface and Presentation API data model to a large extent, and is easily traversable.

However, this can also be a problem, since the developer cannot necessarily know what the side effects of twiddling object properties will be without reading the source, particularly without documentation.

Better documentation of internals, and exposing more events, methods, and "active" configuration outside of the initial setup is something that has come up many times and I think it is now well established that the community wants more granular control of the runtime behaviour and a good AOU to support it. 

I have created [an issue](https://github.com/IIIF/mirador/issues/574) where this api can be discussed in more detail, and will be referencing some related tickets in that thread today.

**Comment by pobocks** [comment]
Not exactly all windows - rather, all windows currently in slots, as a
proxy for "all visible manifests."

The broader scope is that we're not using the localstorage state-saving
mechanism for keeping track of what's open in Mirador, but instead are
using URLs (initially routed through Django, handled via History.js
replace-state on the client).  I was planning on (and still am) writing up
what we're doing as a strawman for anyone else looking to do URL-based link
persistence to beat on.  But, anyway, The client-side portion of it
consists of iterating over slots, getting windows if present, and
processing the manifest into either a local identifier (e.g. drs:12345) or
an external identifier (of form ext:<base64_of_manifest_href>). Then we
append some state info after a $ (technically legal!),  join them with
semicolons (also technically legal!), and voila, all the state we currently
care about is wrapped in the URL.

Anyway, since the goal is "all windows that have a slot,"
getSlotFromAddress isn't useful.  It could be if there's a reliable
property that describes the "shape" of the windowing system, but I haven't
found it yet - the only thing I'm aware of is the initial "1x1"  layout
config var, which only describes regular shapes of interface and isn't
updated when windows are added/removed.

If windows[index].parent == null for all cases where there's no slot, and
is a slot in all other cases, that could work... but it seems to me that a
slot having window == "null" when it's got a perfectly good window is still
a bug, as long as that property exists.

Anyway, if there's a canonical way, while not using the session saving
functionality, to get "what manifests are visible right now," let me know
and I'll use that.  If not, I'll keep poking and try to figure out where
window refs are getting misplaced.

**Comment by rsinghal** [comment]
I can't recreate this bug either, with the latest master, 93396d9ba01ea83f831256c30d7e5e0d2ae00cd6.  If it is still broken for you, can you please add the steps to reproduce?

**Comment by rsinghal** [comment]
Actually, please test with, 292216cf2bcb025f991399d41f39fdd6bcff2bbe.  Old windows were not being removed when their slot was removed, creating orphan windows.

**Comment by pobocks** [comment]
Will do as soon as I get a chance - I'll bet that was it.

**Comment by rsinghal** [comment]
I think you should now be able to do Mirador.viewer.workspace.windows and that should be the equivalent to 'all windows currently in slots, as a proxy for "all visible manifests."'

**Comment by pobocks** [comment]
Oooh, thanks! That's much nicer!

**Comment by rsinghal** [comment]
Can this be closed?

**Comment by pobocks** [comment]
Not going to get to it till tomorrow at the earliest, but if you want to
close it, I can reopen it in the unlikely event that it's not fixed.

**Comment by rsinghal** [comment]
That's fine - we can leave it open until you confirm.

**Comment by rsinghal** [comment]
bump, @pobocks please confirm whether or not this was fixed.

**Comment by pobocks** [comment]
This appears to be fixed!

**Comment by rsinghal** [comment]
Great!
