### ISSUE TITLE
Mirador thumbnail label displays [object object] for multilingual canvas labels

### ISSUE THREAD

**Issue by azaroth42** [IIIF/mirador#653]
For example:

```
{"@type": "sc:Canvas",
 "label": [{"@value": "English", "@language":"en"}, {"@value": "Francais", "@language":"fr"}]
 ...
}
```

**Comment by rsinghal** [comment]
@azaroth42 Do you have a fixture object we can test against?

**Comment by azaroth42** [comment]
Via:
    https://github.com/UniversalViewer/universalviewer/issues/188#issuecomment-176296418

A manifest in the wild that demonstrates this:
    https://iiif.riksarkivet.se/arkis!C0000263/manifest

**Comment by sdellis** [comment]
Just curious, how does the client know which language label to display by default when multiple are provided as in this instance?  (I'm not talking about the metadata panel here.)

**Comment by tomcrane** [comment]
Hi @sdellis - the UV supports a list of locales in preferred order as part of its configuration - which can be used to pull the appropriate metadata from the manifest as well as control the language of the user interface. The user can override the locale. There's also a "toggle" mode in use at the National Library of Wales - so that even if many locales are available to choose from in "settings", the UV draws attention to a toggle between two of them, in this case English and Welsh.

Another option is to use the browser locale, but the UV doesn't do this.

**Comment by sdellis** [comment]
@tomcrane yes, I had a conversation with Ed about this recently, and I like how UV handles it as a config setting/user preference.  I'm sorry, I typed "client" but meant "Mirador" as it was a Mirador issue.  My bad.

**Comment by yuricus** [comment]
We've got intermediate result for fixing this: #806 
This pull request fixes [object object] display to more sensible one (prefers English labels).
To encapsulate language handling new function is created and it's called from different parts of Mirador.

Our small effort creates foundation of working with multilingual labels, I hope that some one will pick it up from here.

**Comment by rsinghal** [comment]
Also related: the label on the manifest view page
