### ISSUE TITLE
Drag manfiest/iiif icon into empty slot and open to a specified canvas.

### ISSUE THREAD

**Issue by aeschylus** [IIIF/mirador#656]
http://zimeon.github.io/iiif-dragndrop/sourcetest.html

**Comment by rsinghal** [comment]
@aeschylus This can be closed, right?

**Comment by aeschylus** [comment]
yep

**Comment by randystern** [comment]
Does not seem to work in Firefox 34.0.5. Does work in Chrome.
Using http://sul-reader-test.stanford.edu/drag_and_drop/  
When I dragged something from Simeon’s demo links page(http://zimeon.github.io/iiif-dragndrop/sourcetest.html )   Mirador does display the “Drop to Load Manifest” arrow, but then nothing happens when I drop the link
