### ISSUE TITLE
Default to rectangle shape when first clicking the Pencil editing tool

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#761]
#748

**Comment by stanislavkostadinov** [comment]
What happens if rectangle is not part of `availableAnnotationDrawingTools` ?
Default value is `"availableAnnotationDrawingTools": ['Rectangle', 'Ellipse', 'Freehand', 'Polygon', 'Pin']`
but a subset of tools without rectangle is possible initial value (e.g. `"availableAnnotationDrawingTools": [ 'Pin']` )

**Comment by rsinghal** [comment]
Excellent point.  Perhaps just the first tool in the array?

**Comment by stanislavkostadinov** [comment]
OK

**Comment by stanislavkostadinov** [comment]
Done
