### ISSUE TITLE
Incorrect metadata value displayed

### ISSUE THREAD

**Issue by mikeapp** [IIIF/mirador#798]
The metadata display repeats the value for a previous label (accession number appears again under bibliography).  The screen shot shows the current version of Mirador vs. an earlier version.  The demo Manifest is http://manifests.britishart.yale.edu/manifest/5009

<img width="776" alt="screen shot 2016-03-18 at 3 25 46 pm" src="https://cloud.githubusercontent.com/assets/1987952/13889717/6642bf36-ed1e-11e5-9e65-4512de45bea6.png">

**Comment by rsinghal** [comment]
We are making the assumption that if the value is an array, then it is an array of objects that provide the same value of that label in multiple languages.  That manifest has an array for `Bibliography` with one string in it.

Before I make the correct fix, this is probably also a question for @azaroth42 since I can't find anything specific one way or the other in the api description.  Is this structure in the manifest valid?

**Comment by azaroth42** [comment]
An array of values with no language associated (e.g. where the values are not objects with @value/@language keys) then it's just a set of values.

The structure in the manifest:

```json
{
 "metadata": [
    {
      "label": "Bibliography",
      "value": ["...", "...", "..."]
    }
  ]
}
```

Is correct.  This is just a case of http://iiif.io/api/presentation/2.0/#repeated-properties, where the property being repeated is `value`.

The content of those strings is not correct, as according to http://iiif.io/api/presentation/2.0/#property-values-in-html if the value is HTML, then it MUST start with `<` and end with `>` but the client should be displaying all of them.

Yes ... the test here is a bit wishy washy to distinguish between a choice based on language and only one should be displayed, and a list where all of the values should be displayed.  The alternative is to always distinguish a choice as a separate resource, which makes it harder to have the strings for the 95% case, and the decision was to be slightly ambiguous.  We could clarify this in http://iiif.io/api/presentation/2.1/#language-of-property-values

**Comment by beaudet** [comment]
Seems reasonable and not questioning the existing spec but why would text with HTML need to start with open bracket and end with close bracket?  What about cases where a string contains simple embedded formatting codes for italics, underline, bold, etc.? Should we start with empty span tag and end with same?

-------- Original message --------

**Comment by azaroth42** [comment]
The requirement to start and end with brackets is to make it clear (or as clear as possible) to distinguish HTML from plain text that might include angle brackets. So the resolution to whether a `< `is a real `<` or the beginning of an HTML tag is the test on the first and last characters of the string.

**Comment by mikeapp** [comment]
@rsinghal noted the cause but for completeness, tested a manifest with `<span>` tags -   http://manifests.britishart.yale.edu/manifest/1004 - and behavior was the same.

**Comment by rsinghal** [comment]
Thanks @mikeapp.  Mirador definitely doesn't handle this correctly, I just wasn't sure what "correct" is. 

For the sake of not going insane in trying to implement this, Mirador will choose one when there are language codes present, or display all if it is an array of string values.  This seems to handle the majority of use cases and I would argue that there needs to be more information in the manifest about how to present it to the user in a meaningful way if neither of those two scenarios are acceptable.

@mikeapp I will also put in the HTML test, which means that the example manifest will not necessarily render the HTML elements correctly, since it doesn't have the `<` and `>` characters, as per @azaroth42's original comment.

@azaroth42 A small clarifying question: does http://iiif.io/api/presentation/2.0/#property-values-in-html assume that there is one root node, as in the example, or is http://manifests.britishart.yale.edu/manifest/1004 also valid, in which there is no root `span` or `p` tag and a series of `span` tags?

**Comment by azaroth42** [comment]
> The content MUST be well-formed XML and therefore must be wrapped in an element such as p or span.

So yes, there must be a single root element.

**Comment by beaudet** [comment]
I suggest a fast fail then.  Perhaps enforce in Mirador 2.1 that properties which might use html formatting fragments inline be minimally wrapped in a (div?) tag. Anything else gets converted to HTML entities at render time.  And I think it makes sense to limit the allowed tags that are not converted to entities both to ensure layout consistency but also to protect against malicious tags.

-------- Original message --------

**Comment by rsinghal** [comment]
Yes, I think these are good ideas @beaudet.  The [API](http://iiif.io/api/presentation/2.0/#property-values-in-html) does indicate that it should remove malicious tags and provides the ability for the client to clean the HTML how it sees fit. 

@aeschylus it feels like the scrubbing should happen in `Manifest` rather than in `MetadataView` so it can be done once.  What do you think?
