### ISSUE TITLE
Expose OSD instance on osdOpen event

### ISSUE THREAD

**Issue by lavigne** [IIIF/mirador#807]
Hello,

I'm trying to add rotation capability as mentioned in [this issue](https://github.com/IIIF/mirador/issues/375). The rotation code mentioned in the issue doesn't seem to be merged into the current release of Mirador. I figured I could get a handle on the OpenSeadragon instance used by Mirador by subscribing the osdOpen event and then using the rotation code given in issue 375 to accomplish this task without altering the Mirador code.  Unfortunately the OpenSeadragon instance isn't passed to the osdEvent handler.  If I add the osd instance as a parameter when the event is fired, everything works as expected.  Can we get the osdOpen event code changed to pass the osd object as a parameter to the event handler?  If that doesn't make sense, I'm just asking to change this line:

`jQuery.publish('osdOpen.'+_this.windowId);`

to this:

`jQuery.publish('osdOpen.'+_this.windowId, _this.osd);`

**Comment by rsinghal** [comment]
Per a discussion during the stand up today, the new iiifManifestsLayout will take over the OSD work, and we will make sure that the OSD object is properly exposed.  Since this is specifically in order to add rotation, and there are plans to add this to release2.1, we are not going to fix this exactly as described, but will make sure this functionality is in release2.1.
