### ISSUE TITLE
Jsonblob endpoint is still requested whereas saveSession is set to false

### ISSUE THREAD

**Issue by regisrob** [IIIF/mirador#811]
_(tested on release2.1 branch)_

**Comment by rsinghal** [comment]
`saveSession` doesn't impact whether or not jsonblob api is being called because it stores (and checks) to local storage.  But, if you have `mainMenuSettings.show` and/or `mainMenuSettings.buttons.bookmark` set to `false`, then it would still call jsonblob.  I have pushed a fix to this in release2.1.  

The only other time it will call jsonblob is if the URL has a jsonblob unique identifier.
