### ISSUE TITLE
TOC code should not assume ranges have a tree structure (or should it?)

### ISSUE THREAD

**Issue by gigamorph** [IIIF/mirador#836]
https://github.com/IIIF/mirador/blob/release2.1/js/src/widgets/toc.js (line 72)

Specifically in getTplData() assumes ranges[0].children is not `undefined` in

```
if (ranges.length < 2) {
  ranges = ranges[0].children;
}
```

This breaks the template helper code when the manifest contains a single `sc:Range` object in structures, setting ranges to `undefined` in the above code.

**Comment by thehabes** [comment]
This also assumes that there is only ever one possible root in the structure when in fact there could be multiple.  Think about this in a typical book structure.  Book is Chapter 1, Chapter 2, and Chapter 3.  Chapter 1 has section1 and section 2, Chapter 2 has section 3 and Chapter 3 has no children.  This caused problems for me because it would never render out Chapter 3 for me.  I had to ignore the ranges.length<2 check and return the ranges gathered from ranges = _this.extractRangeTrees(_this.ranges); to solve this problem.  Here is my getTplData function from my working branch:

getTplData: function() {
      var _this = this,
      ranges = _this.extractRangeTrees(_this.ranges);
      if (ranges.length < 2) {
        //ranges = ranges[0].children; //Why do this?  It doesn't make sense here.  
        /*
            BH edit
            A range can exist outside of a parent.  Therefore, even if the length is just one, we still 
            want to return the array of one range.  The template function checks the one item, realizes it doesn't have
            children and deems it a leaf, which is what we want. 
        */
      }

      return ranges;
    }

This solved all my issues.
