### ISSUE TITLE
PR 840 Redux: Annotation UX Enhancements

### ISSUE THREAD

**Issue by beaudet** [IIIF/mirador#881]
@stanislavkostadinov, please refer to the design document (now a PDF so you don't have to install special fonts or open in MS PowerPoint) for Annotation UX enhancements located here:

https://drive.google.com/file/d/0B8dnsz8s0G6eVWtYZjhvNExDazQ/view?usp=sharing

These enhancements should be made to the annotation branch.

Annotation UX Enhancements
A significant contribution to Mirador by the the ConservationSpace team has been the series of enhancements to annotations that enable additional shapes and styling and editing as well as the ability to create multiple shapes per annotation.  However, there are some fairly straightforward usability enhancements that must be made to the tools.  @rsinghal has reviewed these design proposals and agrees with moving forward with them.

The following improvements to annotation mode will greatly improve the usability of the annotation tools:

1. The annotation cloud icon will appear in two states – gray and white (or the equivalent active / inactive colors / styles of the particular implementation).  Clicking on the cloud icon will toggle between “annotation discovery” mode and “annotations hidden” mode.  The current “X” to dismiss annotation mode will be removed.
2. When in “annotation discovery” mode:
  1. If a user has no annotation editing permissions, they are placed in read-only annotation mode and none of the annotation drawing and styling tools will be displayed and they will not see any options for editing the text of annotations.  
  2. If the user has annotation editing permissions, then the full complement of drawing tools will be displayed.  The “save” and “delete” icons currently displayed to the right of the drawing / styling tools will be removed from the top of the window – they are no longer necessary given other changes requested in this document.  A new pointer tool will be selected by default; only one tool may be selected at a time.  When the pointer tool is selected, the user can navigate the canvas normally, including zooming in and out.  
    1. If a user with editing permissions selects a shape tool, the cursor changes from a pointer to a crosshair. Depressing the mouse button will start to create a new annotation shape.  When the mouse button is released, annotation editing mode is in effect – the tool changes back to a pointer, the new shape’s handles are displayed and the shape is animated. A dialog prompting for annotation text appears with a save and cancel button. 
  3. If a user hovers over an existing annotation while in annotation discovery mode (either within a polygon or on a line of a shape), a hover pop-up appears near the cursor that displays the annotation text in read only mode.  In addition, the shape under the cursor as well as any other shapes associated with the annotation will be visually highlighted by animating the lines that define the perimeter of the shape.  This visually depicts the shapes for the user so they understand which shapes are associated with the annotation.  
    1. If the user has annotation editing permissions, an “edit” and “delete” option will also appear in the pop-up.  
         1.	If a user navigates into the pop-up and selects “delete”, a confirmation dialog appears to confirm the deletion and if the user confirms, the annotation and all shapes associated with it are deleted and persisted to the annotation store.  
         2.	If a user navigates into the pop-up and selects “edit”, the pop-up turns into a moveable dialog window with a text entry widget to edit the annotation text and other annotation metadata. Only shapes associated with the annotation can be selected for shape transformation and styling using the pointer tool.  A “save” and “cancel” option are available in the annotation text dialog.  This mode is called “annotation editing” mode.
            1.	When a shape belonging to the annotation is clicked on with the pointer tool, the transformation handles (dilation, rotation, translation) are activated and, in addition, if there is more than one shape associated with the annotation, a delete shape icon, e.g. trashcan, is displayed in the vicinity of the shape.  If the user clicks on a handle of the selected shape, the system enters “shape editing mode” at which point the shape transformation controls can be used to adjust the shape until the mouse button is released.  When the mouse button is released, the system returns to “annotation editing” mode with the handles of the active shape still highlighted.
            2.	While in “annotation editing mode”, a new shape may be created for the existing annotation by using one of the shape tools and dragging a new shape onto the canvas. 
            3.	The editing dialog can be moved out of the way as necessary to create and edit shapes.  The window movement bar for this dialog should be widened slightly to permit it to be grabbed more easily as this will be a common operation performed by users.
            4.	If “save” is clicked in the annotation editing dialog, any changes made to shapes or the annotation text for that annotation, are persisted to the annotation store.  The user interface then reverts to annotation discovery mode.
            5.	If “cancel” is clicked, any changes made to shapes or the annotation text are reverted to their prior state and the system re-enters “annotation discover” mode.
            6.	While in annotation editing mode, if the user clicks on the annotation icon to enter “annotations hidden” mode or navigates to another canvas, the action should be treated equivalently to a “cancel” operation from the annotation text dialog.

In order to minimize the size of the PRs and to faciliate a faster review, please consider submitting PRs for the following functionality sets:

PR #1 {Drawing Menu Modifications Set A: Delete the X icon and the editing icon that currently appear when the annotation cloud icon is clicked and make the cloud icon toggle between active and inactive, displaying the pointer and all drawing tools and the annotation reload icon when active and user has editing permissions.  Select the pointer tool by default whenever drawing tools are revealed.  Make sure that only the pointer or one of the drawing shapes can be selected at a time.  When no shape tool is selected, user may continue to pan the canvas using mouse clicking / dragging.  They should always be able to use the scroll wheel, except perhaps when creating a new shape or transforming an existing one.  When there’s an active shape user can draw shapes with the mouse} - See design document.
PR #2 { Annotation Shape Highlighting: when in annotation discovery mode, and user hovers over a shape, all shapes associated with the annotation are highlighted using a CSS border animation and a pop-up appears to display the text of the annotation along with edit / delete buttons based on user’s permissions} - See design document.
PR #3 {Annotation Delete and Delete confirmation: when user selects “delete” from annotation pop-up, they receive a confirmation dialog prior to the system deleting the entire annotation}. See design document.
PR #4 {Annotation Editing Mode: support for adding additional shapes to an annotation, deleting existing shapes from an annotation, and limiting the shapes that can be selected after clicking on “edit” to the current annotation.  Ensure the editing dialog is easily moved without closing it.  Support for cancelling the annotation editing mode when user clicks on high level annotation icon.} -  See design document.

**Comment by rsinghal** [comment]
@radpet I have started working on some of the first items listed in this issue on `881-annotation-controls`.  It had to be separate from `annotation-work` because I needed to include work on the canvas controls in general (coming from `789-canvas-controls`).  @beaudet mentioned that improving the editing an entire annotation (the text and the associated shapes) is on your radar, so I wanted you to be aware of this initial work

**Comment by radpet** [comment]
@rsinghal  I have already implemented the basic hovering as you can see in annotation-work (without the permission check).

> c. If a user hovers over an existing annotation while in annotation discovery mode (either within a polygon or on a line of a shape), a hover pop-up appears near the cursor that displays the annotation text in read only mode. In addition, the shape under the cursor as well as any other shapes associated with the annotation will be visually highlighted by animating the lines that define the perimeter of the shape. This visually depicts the shapes for the user so they understand which shapes are associated with the annotation.

Currently I am refactoring the stroke style picker from https://github.com/IIIF/mirador/pull/840 in order to merge it into annotation work (I should be ready by tomorrow)

Regarding the Annotation UX Enhancements I tried to give estimation to most of the topics above and gave it to @beaudet. 

I am about to start implementing the pointer tool and refactor the hud control in order to support only
> “annotation discovery” mode and “annotations hidden” mode.
(Are you doing this right now ?)
I am also planning to give proposal for permission system (based on the annotation endpoint architecture) in order to make it configurable. I will need it in order to fulfill the requirements above (When to show the other tools,when to allow annotation edit/delete)

**Comment by rsinghal** [comment]
@radpet I have implemented #1 in `881-annotation-controls`, but it is not yet done (especially with regards to the border and fill color menus).

I have removed the extra step of clicking to get to the drawing/editing mode

2.iii.b and everything related to that still needs to be done.  I have not done any work on that yet.

**Comment by radpet** [comment]
@rsinghal Sounds great, okey I after I end with the stroke style picker I might start working on the pointer tool , which will be the default tool when entering into annotation mode.

**Comment by rsinghal** [comment]
@radpet I am working on 2.iii.b and the first thing I'm trying to do is when the user clicks 'edit' from the text box, Mirador figures out what shapes are associated with that annotation text.  I made a change in osd-region-draw-tool, https://github.com/IIIF/mirador/blob/annotation-work/js/src/annotations/osd-region-draw-tool.js#L141, to use the annotation id in the map.  However, that just gives me the paths, but I'm not sure how to take those paths and get overlay objects out of them, https://github.com/IIIF/mirador/blob/annotation-work/js/src/annotations/osd-region-draw-tool.js#L272.  Do you know how to do that?

**Comment by radpet** [comment]
@rsinghal As far as I understand you, you when you have the paths you should loop them and then find the corresponding tool which controls given shape path.
Look for example how I implemented the hovering :
https://github.com/IIIF/mirador/commit/742aefaf4af4274fc77a614999bfd92a0eb08098

https://github.com/IIIF/mirador/blob/release2.1/js/src/annotations/osd-svg-rectangle.js#L78

In addition to 2.iii.b I think to implement this functionality you should keep some flag in path.data in order to know if it can be selected. And when the user clicks edit to mark it as ready for edit.

**Comment by rsinghal** [comment]
@radpet I will add a boolean to `path.data` that can be updated when a user hits edit, save, and cancel, which can then be checked before triggering the mouse events.  That makes sense to me.

I think it would be useful to the user to have some sort of visual clue when they hit edit, which shapes are actually editable.  It could either be they see the handles on all of the shapes they can edit, or we nearly hide away all of the other shapes, or something like that.  What I can't figure out is how to trigger an event that svg-overlay is listening for based on the `path` object in order to cause the visual change in each overlay.  Basically, in https://github.com/IIIF/mirador/blob/annotation-work/js/src/annotations/osd-region-draw-tool.js#L272, I want to do `_this.eventEmitter.publish('enableOverlay.' + _this.windowId)` and also pass it information that says what kind of tool it is so svg-overlay can be listening for that event and the trigger the proper tool.  I'm not seeing anything in `path.data` that indicates the tool, or am I missing something?

**Comment by radpet** [comment]
You won't see reference to the tool in path data. You should loop through
the available tools and match the name of the path to the id of the tool
with
path._name.indexOf(tool.idPrefix) !== -1
If this is true this is the tool for this shape

**Comment by rsinghal** [comment]
I see - thanks!

**Comment by radpet** [comment]
@beaudet @rsinghal   Where I can get the rotation handle icon and trash can images from?

**Comment by rsinghal** [comment]
@radpet I think the best way forward is to have the rotate and trashcan icons always appear (instead of only on mouse over or mouse down) at the top of the shape.  You can use the font awesome icons for them, but since you don't have to worry about changing the CSS cursor property, you don't have to worry about having separate img files.

**Comment by radpet** [comment]
@rsinghal  Currently I use http://paperjs.org/reference/raster/ to load image and then I attach it to the shape when it is active (when it was clicked)  and detach it when it was deactivated (other shape was clicked or mode changed).

I am talking about this mockup https://drive.google.com/file/d/0B8dnsz8s0G6eVWtYZjhvNExDazQ/view
I am currently working to make the shape look like slide 9

**Comment by rsinghal** [comment]
I mean have rotate and trashcan visible only when the shape has been selected.  So the new flow is:

User chooses to edit an annotation through the text viewer.  This switches to the text editor and Mirador sets which shapes are editable (I am currently playing around with adjusting the stroke width of editable shapes).  If a user clicks one of those editable shapes, they get the normal handles and see the rotate and trashcan icons by the top handle.  If they deselect it, those icons and handles disappear.  If the user clicks on an non-editable shape, nothing happens.

**Comment by radpet** [comment]
@rsinghal  Yup same here, 

> We need to create "selected" state for a shape that sets things like handles, icons, etc and a "deselected" state that removes those.

Currently we have this by using the  ``updateSelection function``. 

@beaudet @rsinghal 
Okey I'll start working on the trash can now. However I have some questions regarding its position: 
Where should we attach it?
For rectangles and ellipses it is rather easy - oposite the rotate icon
pins - at the bottom
polygon - down lowest point of all points? Near the middle of the longest/shortest line?
What about freehand tool?

**Comment by beaudet** [comment]
polygon and freehand - below the lowest point vertically but in geometric center of all points would probably work and should be consistent with the other shapes

**Comment by radpet** [comment]
@beaudet @rsinghal 

I am almost ready with the new edit shape workflow but I have a question:

When user edits existing annotation and want to create shape he chooses tool from the menu and draw a shape. What happens next, is the tool he has chosen remains the same or to draw again he should choose the tool from the menu again?

Currently the current active tool is the one you last used or if you have clicked on shape for transformation the tool that handles the transformation.

You can check it out on this branch https://github.com/SirmaITT/mirador/tree/feature/polygon-freeshape-pin-editable

**Comment by rsinghal** [comment]
@radpet Have you looked at the behavior that is currently in `annotation-work`?  I have already implemented most of these changes, with regard to editing an annotation.  The main thing is it is not fully working for polygons and freeform because of the refactoring that you needed to complete.

For 1) when adding new shapes to an existing annotation, it stays on that shape until the user clicks save or cancel.  This behavior already exists in `annotation-work`

3) It is now impossible to select a shape to edit it unless you've clicked `Edit` on the annotation text viewer and at that point you can only edit shapes associated with that annotation.  This is also in `annotation-work`

**Comment by beaudet** [comment]
I'm fine with all of this as it sounds completely usable to me based on the descriptions.  Can't wait to see it working in CSPACE!

**Comment by radpet** [comment]
@rsinghal I agree with you but you are partly right here, currently in annotation-work they don't work always.

Go check those use cases:

Create annotation with a rectangle shape.

Use case 1 (1st point)

Go to the rectangle shape.Click edit on the popup.
Choose another tool and create additional shape. After you have finished drawing, try to select the first rectangle, you will need 2 hit to activate it (this is because the overlay goes out of edit annotation mode, which it should not).

Use case 2 (3rd point):
You are in annotation discovery mode (pointer tool has been selected)
Select rectangle tool
Select the rectangle shape you previously created. See that it is selected and you can transform it, although you can't save that transformation.

Please tell me if you need more information. I will make a video if you need.

**Comment by rsinghal** [comment]
@radpet You are quite right - I had not noticed that behavior.

1) You are right, after a user draws a new shape, while editing an annotation, and then clicks on an existing shape, Mirador should switch them back to edit mode for that shape.

3) Correct - it should not be possible to click on a shape unless in edit mode.  So that can be removed completely.

**Comment by rsinghal** [comment]
I think we have finally addressed everything in this.  Closing it.  We can create any new, smaller, tickets that still need to be addressed.

**Comment by radpet** [comment]
@rsinghal There two things left I think, 
the cursor change on mouse down/move and the blue doth to become icon such as the trash can

**Comment by rsinghal** [comment]
Yes, if you could make an issue for the rotation handle since we have #1012 for the cursor
