### ISSUE TITLE
TOC child range toggle not working in release 2.1

### ISSUE THREAD

**Issue by thehabes** [IIIF/mirador#939]
http://165.134.241.141/brokenBooks/getManifest.html

When I click on a caret, _this.render() always fires

toClose = _this.previousSelectedElements.filter(function(rangeID) {...})

and never 

toOpen = _this.selectedElements.filter(function(rangeID) {...})

It seems like no matter what, it is always trying to close the first listed range and the variable toOpen is always an empty array.  See the web console log for additional information.

**Comment by thehabes** [comment]
To make this work, I changed the click event on the carets to the following so it works while I investigate:

      _this.element.find('.toc-caret').on('click', function(event) {
             var caret = this;
             event.stopPropagation();
             var rangeID = jQuery(this).parent().data().rangeid;
             _this.setOpenItem(rangeID);
             //_this.render();
             //This way does not open up the list.  The event is detected, but it always calls close
             //Below is the old way, and it works
            jQuery(caret).parents("li:first").toggleClass('open').find('ul:first').slideFadeToggle();
      });

**Comment by aeschylus** [comment]
I will look into this. The tree is a complex feature and can't really be addressed by manipulating the DOM inside a handler. Please read: http://nicolashery.com/describing-ui-state-with-data/

The reason render is always called is that the setter updates the centralised data representation of UI state, so that render can render that state. The appearance of the UI should be a "pure function" of the UI state - the same input should always produce identical output. So, for instance, in your anonymous event handler, you update the DOM. No other event handler will be able to account for that change, so I might forget later to twiddle everything off in another handler, and the user will get some weird double-selected state. It also makes it very hard to write tests. 

I imagine I didn't correctly update the render function when I refactored this (the bug wasn't caught by tests I didn't have), so the render function would be a good place to look for/submit a fix. Also a test would help. I should be able to have a look at this earlier next week. 

Thanks for the good catch @thehabes.

**Comment by jeffreycwitt** [comment]
Not sure if the "ready" label means this has been fixed. But I'm still getting this error after pulling the most recent commit c03cc14184ff6749b0d6096bbb2a9ba7598ac799 as of July 30

**Comment by aeschylus** [comment]
Seems to also not load correctly on initially opening.
