### ISSUE TITLE
Annotations don't rotate with the canvas

### ISSUE THREAD

**Issue by dicksonlaw583** [IIIF/mirador#984]
Try viewing the following manifest with annotations on:

http://wellcomelibrary.org/iiif/b18035723/manifest

Rotating the canvas would leave the annotations placed in their original positions out-of-sync.

In addition, I found several rotation-related functions on OpenSeaDragon's online documentation that may help fix this, but implementing them would require bumping up the version of OpenSeaDragon used in the source since I can't find them there. Would that be a possibility in the short-term?

**Comment by aeschylus** [comment]
Good catch @dicksonlaw583. We should write some tests for this. I don't think it will be the best use of time to try to address this directly now, since there will probably be some changes once the IIIFManifestLayouts work gets merged in. It's worth researching though. I will also ensure that the IIIFML code is using the most up-to-date seadragon.

**Comment by dicksonlaw583** [comment]
I attempted upgrading the built-in OpenSeaDragon, but failed due to a significant number of deprecation-related errors. In the meanwhile, I have found a stopgap fix that will clear the bug with the existing OSD, so we have options now.
