### ISSUE TITLE
Be able to delete points in a polygon annotation in "edit" mode

### ISSUE THREAD

**Issue by rsinghal** [IIIF/mirador#986]

**Comment by radpet** [comment]
@rsinghal I am currently implementing this as part of https://github.com/SirmaITT/mirador/tree/feature/polygon-freeshape-pin-editable,
however I have a problem. When the editor is active it intercepts the key events and stops them from propagating. I am thinking about focusing the canvas when it is clicked in order to remove the focus from the editor. What do you think? Any other suggestions?

**Comment by rsinghal** [comment]
Do you mean the annotation editor?  I think your workaround seems reasonable right now.  We can always create a ticket for this separately at a later date to investigate it further.

**Comment by radpet** [comment]
@rsinghal Yup, TinyMce is preventing the event propagation. 
It all works now (holding shift and selecting point will remove it), except that the polygon tool does not support adding additional points to existing polygon. (I think this should be implemented as part of another ticket/pr)

**Comment by rsinghal** [comment]
Agreed.  It should be separate and perhaps not a high priority, at the moment.

**Comment by radpet** [comment]
@rsinghal Another use case that we don't handle yet is if the polygon was/wasn't closed what will be its closed state after edit. However by implementing an algorithm to check if drawn shape is closed or not we will eliminate those problems.

**Comment by radpet** [comment]
In addition I have implemented functionality that allows you to delete segment points from freehand drawing too, by holding shift button again :)

**Comment by radpet** [comment]
@rsinghal I thnk this is ready to be closed :)
